// <auto-generated />
using System;
using MaintenanceManagementApi.Data.DataDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaintenanceManagementApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241011074137_initdatabase")]
    partial class initdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaintenanceManagementApi.Data.DBModel.Right", b =>
                {
                    b.Property<int>("RightsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RightsID"));

                    b.Property<string>("RightsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RightsID");

                    b.ToTable("Rights");
                });

            modelBuilder.Entity("MaintenanceManagementApi.Data.DBModel.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MaintenanceManagementApi.Data.DBModel.RoleRight", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("RightsID")
                        .HasColumnType("int");

                    b.HasKey("RoleID", "RightsID");

                    b.HasIndex("RightsID");

                    b.ToTable("RoleRights");
                });

            modelBuilder.Entity("MaintenanceManagementApi.Data.DBModel.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MaintenanceManagementApi.Data.DBModel.RoleRight", b =>
                {
                    b.HasOne("MaintenanceManagementApi.Data.DBModel.Right", "Right")
                        .WithMany("RoleRights")
                        .HasForeignKey("RightsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaintenanceManagementApi.Data.DBModel.Role", "Role")
                        .WithMany("RoleRights")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Right");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MaintenanceManagementApi.Data.DBModel.User", b =>
                {
                    b.HasOne("MaintenanceManagementApi.Data.DBModel.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MaintenanceManagementApi.Data.DBModel.Right", b =>
                {
                    b.Navigation("RoleRights");
                });

            modelBuilder.Entity("MaintenanceManagementApi.Data.DBModel.Role", b =>
                {
                    b.Navigation("RoleRights");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
